#pragma once
// Default SSID list — stored in flash, not RAM. Safe at any size on 4MB+ ESP32.
// Replace or extend by running:  python3 tools/wigle_fetch.py --gen 2000

#define NUM_SSIDS 1500

static const char* const ssid_list[] = {

    // ── Xfinity / Comcast ──────────────────────────────────────────────────
    "XFINITY","xfinitywifi","xfinity","XFINITY-2G","XFINITY-5G",
    "XFINITY-A2F4","XFINITY-B3C7","XFINITY-D1E9","XFINITY-F4A2","XFINITY-8C3E",
    "XFINITY-1B4D","XFINITY-7A9F","XFINITY-2E5C","XFINITY-4B8A","XFINITY-C6D3",
    "xfinity3F9C","xfinity7B2A","xfinityE4F1","xfinity2C8D","xfinity9A3B",
    "Comcast-2G-4A1B","Comcast-5G-4A1B","ComcastWiFi-3C2D","ComcastWiFi4G",
    "Comcast-2G-F7E2","Comcast-5G-B3C1","ComcastWiFi-A4D6","Comcast-9E5F",
    "MySpectrumWiFi-3A1","MySpectrumWiFi-B7C2","MySpectrumWiFi2G-4F9","MySpectrumWiFi5G-C2A",

    // ── Spectrum ───────────────────────────────────────────────────────────
    "Spectrum-A4B3","Spectrum-3F2E","Spectrum-C9D1","Spectrum-7A4E","Spectrum-B2F6",
    "Spectrum-2G-A1B2","Spectrum-5G-A1B2","Spectrum-2G-C3D4","Spectrum-5G-E5F6",
    "Spectrum-2G-9E7F","Spectrum-5G-2B4C","Spectrum-2G-F1A3","Spectrum-5G-8D2E",
    "SpectrumWiFi-6G","SpectrumWiFi4G-3A2B","SpectrumWiFi-A7B1","SpectrumWiFi-D4E8",
    "SpectrumWiFi2-B3C","SpectrumSetup-A1","SpectrumExt-4F2","TWC-WIFI-A1B2",

    // ── AT&T ──────────────────────────────────────────────────────────────
    "ATT-WIFI-A1B2","ATT-WIFI-3C4D","ATT-WIFI-E5F1","ATT-WIFI-7B9C",
    "ATTWifi-E5F1","ATTWifi-2A3B","ATTWifi-C7D4","ATTWifi-9F1E",
    "ATT-WiFi-2G","ATT-WiFi-5G","att-wifi-A4C2","att-wifi-F3B7",
    "ATTUNITVERSE-A1","ATTUNITVERSE-C3","ATT-DSL-A1B2","ATT-U-verse",
    "ATT-WiFi-A3B5","ATT-WiFi-D2E8","ATT-WiFi-6C4F","ATTWifi-B8A3",
    "att5G-A1B2","att2G-C3D4","AT&T-WiFi","AT&T-2.4G","AT&T-5G",

    // ── CenturyLink / Lumen ────────────────────────────────────────────────
    "CenturyLink-A1B2","CenturyLink-3C4D","CenturyLink5G-E1F2","CenturyLink2-A3B4",
    "CenturyLink-C9D7","CenturyLink-7E3F","CenturyLink5G-B4C8","CenturyLink2-D1E5",
    "CenturyLinkA3F1","CenturyLink-2.4GHz","CenturyLink-5GHz",
    "Lumen-WiFi-A1","Quantum-WiFi-B2","Qwest-A1B2","CenturyTel-A1",

    // ── Cox ────────────────────────────────────────────────────────────────
    "Cox-WiFi-A1B2","Cox-WiFi-3C4D","CoxWiFi-E5F6","Cox-2G-A1","Cox-5G-A1",
    "CoxWifi3F2A","CoxWifi-B4C7","CoxWifi-D9E1","Cox-2G-F3B5","Cox-5G-A8C2",
    "CoxWifi_EXT","CoxBusiness-A1","Cox-Security-A1","Cox-Homelife",

    // ── Verizon / Fios ─────────────────────────────────────────────────────
    "Verizon-FIOS-A1B2","Verizon-FIOS-C3D4","FIOS-A1B2","FIOS-E5F6",
    "VerizonMiFi-A1B2","VerizonWiFi-5G","VerizonWiFi-2G","Verizon-A3C7",
    "FIOS-B2D4","FIOS-9E1F","FiOS-Router-A1","Verizon-G1100",
    "VZW-HOTSPOT-A1","VZW-A1B2","Verizon-LTE-A1","Verizon-5G-Home",

    // ── Frontier ──────────────────────────────────────────────────────────
    "FrontierWifi-A1","FrontierWifi-3C","Frontier-2G-A1B2","Frontier-5G-A1B2",
    "FrontierWifi-B4C9","FrontierWifi-D2E7","Frontier-A4F1","FrontierHSI-A1",

    // ── Other US ISPs ──────────────────────────────────────────────────────
    "RCN-A1B2","Optimum-A1B2","Optimum-5G-A1","Optimum-2G-B2",
    "Mediacom-A1B2","Mediacom-5G","WOW-A1B2","WOW-WiFi",
    "BrightHouse-A1B2","TDS-WiFi-A1B2","TDS-A3C5","Windstream-A1B2",
    "SuddenLink-A1B2","SuddenLink-5G","HughesNet-A1B2","Starlink","starlink-guest",
    "CableOne-A1B2","WideOpen-A1B2","Consolidated-A1B2",
    "MetroNet-A1","Ziply-A1B2","Ting-A1B2","EPB-A1B2",
    "GoogleFiber-A1","Google-Fiber","GFiber-2.4G","GFiber-5G",

    // ── NETGEAR ────────────────────────────────────────────────────────────
    "NETGEAR-A1B2","NETGEAR-3C4D","NETGEAR-E5F6","NETGEAR-7890",
    "NETGEAR-B4C9","NETGEAR-F1A7","NETGEAR-2D3E","NETGEAR-8C5F",
    "NETGEAR-A1B2-5G","NETGEAR-C3D4-5G","NETGEAR_EXT","NETGEAR-2.4G","NETGEAR-5G",
    "NETGEAR-6G","Nighthawk-A1B2","Nighthawk-2.4G","Nighthawk-5G","Nighthawk-6G",
    "Orbi-A1B2","Orbi-5G-A1B2","Orbi-6G-A1","OrbiBackhaul","ORBI60-A1B2",
    "ORBI70-A1B2","Orbi-2.4G","Orbi-A3C7","Orbi-B9D2","Orbi-4F1E",

    // ── Linksys ────────────────────────────────────────────────────────────
    "linksys","Linksys","LINKSYS","linksys-A1B2","linksys-3C4D",
    "Linksys-5G-A1B2","Linksys-2.4GHz","Linksys-5GHz","Linksys-6GHz",
    "linksys-B7C3","linksys-D4E9","Linksys-F2A5","Linksys-8E1C",
    "Velop-A1B2","Velop-5G-A1","VelopMesh-A1","Linksys-MX4200",

    // ── D-Link ─────────────────────────────────────────────────────────────
    "dlink","DLINK","D-Link","D-Link-A1B2","D-Link-3C4D","dlink-A1B2-5G",
    "D-Link-B9C4","D-Link-7E2F","dlink-C3A8","D-Link-5G-A1B2",
    "D-Link-2.4G","D-Link-6G","dlink-EXT","DIR-878-A1",

    // ── ASUS ───────────────────────────────────────────────────────────────
    "ASUS_RT-A1B2","ASUS_A1B2","AsusWiFi-A1","ASUS-2G","ASUS-5G",
    "ASUS_RT-B3C7","ASUS_D1E9","ASUS-6G","ASUS-AX","ASUS-AiMesh",
    "ASUS_C4F2","ASUS-RT-A1","ASUSWRT-A1","AsusWiFi-B4","ROG-A1B2",
    "ROG-Rapture-A1","ASUS-Gaming","ZenWiFi-A1B2","ZenWiFi-5G",

    // ── TP-Link ────────────────────────────────────────────────────────────
    "TP-LINK_A1B2","TP-LINK_3C4D","TP-Link_A1B2","TP-LINK-5G-A1",
    "TPLINK-A1B2","TP-LINK_EXT","TP-Link_Extender","TP-LINK-2.4G",
    "TP-LINK_B7C3","TP-LINK_D4E9","TP-Link_F1A6","TP-LINK_2E8C",
    "Archer_A1B2","Archer_3C4D","ArcherAX50-A1","ArcherC7-A1",
    "Archer-AX73-A1","Deco-A1B2","Deco-5G","DecoMesh-A1",
    "Tapo-A1B2","Tapo-2.4G","Tapo-5G",

    // ── eero / Amazon ─────────────────────────────────────────────────────
    "eero","eero 5G","eero-2.4GHz","eeroNetwork","eero-A1B2",
    "eero-B3C7","eero-D9E2","eero-A4F1","eero 6","eero Max",
    "Amazon-A1B2","amazon-extension","Amazon-Eero-A1B2","eero Pro",
    "Amazon Echo","Amazon-Smart-Home",

    // ── Google / Nest ──────────────────────────────────────────────────────
    "Google-Home","GoogleHome-A1B2","Google-Nest-WiFi","GoogleWifi-A1B2",
    "Nest-A1B2","Nest-5G-A1B2","Google-WiFi","NestWifi-A1","NestWifi-B2",
    "GoogleFiber-A1","Google-AC1900","Nest-Hub","Nest-Wifi-A3C",

    // ── Belkin / Wemo ──────────────────────────────────────────────────────
    "Belkin.A1B2","Belkin_A1B2","BelkinA1B2","Belkin-5G","Belkin.3C4D",
    "Belkin.E5F6","Belkin-N300","Belkin-AC1200","Wemo-A1B2",

    // ── Other routers ──────────────────────────────────────────────────────
    "Arris-A1B2","ARRIS-A1B2","SBG10-A1","SBG6580-A1","Arris-5G",
    "Motorola-A1B2","Motorola-5G","MG7700-A1","MB8600-A1",
    "Technicolor-A1B2","Technicolor-5G","Hitron-A1B2","Hitron-5G",
    "2WIRE-A1B2","BellSouth_A1B2","SBC_A1B2","Westell-A1",
    "Ubiquiti-A1B2","UniFi-A1B2","UAP-AC-PRO","AmpliFi-A1",
    "Synology-A1B2","QNAP-A1B2","Airport_Network","AirPort-A1B2",
    "Time Capsule-A1B2","HUAWEI-A1B2","HUAWEI-WiFi-A1","HUAWEI-5G",
    "ZTE_A1B2","ZTE-A1B2","ZTE-F670","ZTE-5G","Zyxel-A1B2",
    "Mikrotik-A1","pfSense-A1","Cisco-A1B2","Meraki-A1",
    "GL-iNet-A1","Gl.iNet-A1","Firewalla-A1","Peplink-A1",

    // ── Residential: Smith through Cruz (50+ last names × patterns) ────────
    "Smith-WiFi","Smith-Net","Smith-Home","Smiths-WiFi","The Smiths",
    "Jones-WiFi","Jones-Net","Jones-Home","Jones Family","JonesWifi",
    "Johnson-Net","Johnson-WiFi","Johnson-Home","JohnsonNet",
    "Williams-Home","Williams-WiFi","Williams-Net","WilliamsWifi",
    "Brown-2G","Brown-5G","Brown-WiFi","Brown-Net","BrownHome",
    "Davis-WiFi","Davis-Net","Davis-Home","Davis Family",
    "Miller-Net","Miller-WiFi","Miller-Home","MillerWifi",
    "Wilson-Home","Wilson-WiFi","Wilson-Net","WilsonNet",
    "Anderson-WiFi","Anderson-Net","Anderson-Home",
    "Taylor-Net","Taylor-WiFi","Taylor-Home","Taylor Family",
    "Thomas-WiFi","Thomas-Net","Thomas-Home",
    "Jackson-Home","Jackson-WiFi","Jackson-Net",
    "White-Network","White-WiFi","White-Net","WhiteWifi",
    "Harris-WiFi","Harris-Net","Harris-Home","HarrisNet",
    "Martin-Net","Martin-WiFi","Martin-Home",
    "Thompson-Home","Thompson-WiFi","Thompson-Net",
    "Garcia-WiFi","Garcia-Net","Garcia-Home","Garcia Family",
    "Martinez-Net","Martinez-WiFi","Martinez-Home",
    "Robinson-Home","Robinson-WiFi","Robinson-Net",
    "Clark-WiFi","Clark-Net","Clark-Home","ClarkNet",
    "Rodriguez-Net","Rodriguez-WiFi","Rodriguez-Home",
    "Lewis-Home","Lewis-WiFi","Lewis-Net",
    "Lee-WiFi","Lee-Net","Lee-Home","LeeWifi",
    "Walker-Net","Walker-WiFi","Walker-Home",
    "Hall-Home","Hall-WiFi","Hall-Net","HallNet",
    "Allen-WiFi","Allen-Net","Allen-Home",
    "Young-Net","Young-WiFi","Young-Home","Young Family",
    "Hernandez-Home","Hernandez-WiFi","Hernandez-Net",
    "King-WiFi","King-Net","King-Home","KingWifi",
    "Wright-Net","Wright-WiFi","Wright-Home",
    "Lopez-Home","Lopez-WiFi","Lopez-Net","Lopez Family",
    "Hill-WiFi","Hill-Net","Hill-Home","HillNet",
    "Scott-Net","Scott-WiFi","Scott-Home",
    "Green-Home","Green-WiFi","Green-Net","GreenNet",
    "Adams-WiFi","Adams-Net","Adams-Home",
    "Baker-Net","Baker-WiFi","Baker-Home","BakerWifi",
    "Nelson-Home","Nelson-WiFi","Nelson-Net",
    "Carter-WiFi","Carter-Net","Carter-Home","Carter Family",
    "Mitchell-Net","Mitchell-WiFi","Mitchell-Home",
    "Perez-Home","Perez-WiFi","Perez-Net",
    "Roberts-WiFi","Roberts-Net","Roberts-Home",
    "Turner-Net","Turner-WiFi","Turner-Home",
    "Phillips-Home","Phillips-WiFi","Phillips-Net",
    "Campbell-WiFi","Campbell-Net","Campbell-Home",
    "Parker-Net","Parker-WiFi","Parker-Home",
    "Evans-Home","Evans-WiFi","Evans-Net",
    "Edwards-WiFi","Edwards-Net","Edwards-Home",
    "Collins-Net","Collins-WiFi","Collins-Home",
    "Stewart-WiFi","Stewart-Net","Stewart-Home",
    "Sanchez-Net","Sanchez-WiFi","Sanchez-Home",
    "Morris-Home","Morris-WiFi","Morris-Net",
    "Rogers-WiFi","Rogers-Net","Rogers-Home",
    "Reed-Net","Reed-WiFi","Reed-Home",
    "Cook-WiFi","Cook-Net","Cook-Home",
    "Morgan-Home","Morgan-WiFi","Morgan-Net",
    "Bell-WiFi","Bell-Net","Bell-Home",
    "Murphy-Net","Murphy-WiFi","Murphy-Home",
    "Bailey-Home","Bailey-WiFi","Bailey-Net",
    "Rivera-WiFi","Rivera-Net","Rivera-Home",
    "Cooper-Net","Cooper-WiFi","Cooper-Home",
    "Richardson-WiFi","Richardson-Net",
    "Cox-Home","Cox-Net-Private","Cox-Family",
    "Howard-WiFi","Howard-Net","Howard-Home",
    "Ward-Net","Ward-WiFi","Ward-Home",
    "Torres-Home","Torres-WiFi","Torres-Net",
    "Peterson-WiFi","Peterson-Net","Peterson-Home",
    "Gray-Net","Gray-WiFi","Gray-Home",
    "Ramirez-WiFi","Ramirez-Net","Ramirez-Home",
    "James-Home","James-WiFi","James-Net",
    "Watson-WiFi","Watson-Net","Watson-Home",
    "Brooks-Net","Brooks-WiFi","Brooks-Home",
    "Kelly-Home","Kelly-WiFi","Kelly-Net",
    "Sanders-WiFi","Sanders-Net","Sanders-Home",
    "Price-Net","Price-WiFi","Price-Home",
    "Bennett-Home","Bennett-WiFi","Bennett-Net",
    "Wood-WiFi","Wood-Net","Wood-Home",
    "Barnes-Net","Barnes-WiFi","Barnes-Home",
    "Ross-Home","Ross-WiFi","Ross-Net",
    "Henderson-WiFi","Henderson-Net","Henderson-Home",
    "Coleman-Net","Coleman-WiFi","Coleman-Home",
    "Jenkins-Home","Jenkins-WiFi","Jenkins-Net",
    "Perry-WiFi","Perry-Net","Perry-Home",
    "Powell-Net","Powell-WiFi","Powell-Home",
    "Long-Home","Long-WiFi","Long-Net",
    "Patterson-WiFi","Patterson-Net",
    "Hughes-Net-Home","Hughes-WiFi",
    "Flores-Home","Flores-WiFi","Flores-Net",
    "Washington-WiFi","Washington-Net",
    "Butler-Home","Butler-WiFi","Butler-Net",
    "Simmons-WiFi","Simmons-Net","Simmons-Home",
    "Foster-Net","Foster-WiFi","Foster-Home",
    "Gonzales-WiFi","Gonzales-Net",
    "Bryant-Home","Bryant-WiFi",
    "Alexander-Net","Alexander-WiFi",
    "Russell-Home","Russell-WiFi",
    "Griffin-WiFi","Griffin-Net",
    "Diaz-Home","Diaz-WiFi","Diaz-Net",
    "Hayes-Net","Hayes-WiFi","Hayes-Home",
    "Myers-WiFi","Myers-Net","Myers-Home",
    "Ford-Home","Ford-WiFi","Ford-Net",
    "Hamilton-WiFi","Hamilton-Net",
    "Graham-Net","Graham-WiFi","Graham-Home",
    "Sullivan-WiFi","Sullivan-Net",
    "Wallace-Home","Wallace-WiFi",
    "Woods-Net","Woods-WiFi","Woods-Home",
    "Cole-WiFi","Cole-Net","Cole-Home",
    "West-Home","West-WiFi","West-Net",
    "Jordan-WiFi","Jordan-Net","Jordan-Home",
    "Owens-Net","Owens-WiFi",
    "Reynolds-Home","Reynolds-WiFi",
    "Fisher-WiFi","Fisher-Net","Fisher-Home",
    "Ellis-Net","Ellis-WiFi","Ellis-Home",
    "Harrison-WiFi","Harrison-Net",
    "Gibson-Home","Gibson-WiFi",
    "Mcdonald-WiFi","McDonald-Net",
    "Cruz-Home","Cruz-WiFi","Cruz-Net",
    "Marshall-WiFi","Marshall-Net",
    "Ortiz-Home","Ortiz-WiFi","Ortiz-Net",
    "Gomez-WiFi","Gomez-Net","Gomez-Home",
    "Murray-Net","Murray-WiFi",
    "Freeman-Home","Freeman-WiFi",
    "Wells-WiFi","Wells-Net","Wells-Home",
    "Webb-Net","Webb-WiFi","Webb-Home",
    "Simpson-WiFi","Simpson-Net",
    "Stevens-Home","Stevens-WiFi",
    "Tucker-WiFi","Tucker-Net","Tucker-Home",
    "Porter-Net","Porter-WiFi",
    "Hunter-Home","Hunter-WiFi","Hunter-Net",
    "Hicks-WiFi","Hicks-Net",
    "Crawford-Home","Crawford-WiFi",
    "Henry-WiFi","Henry-Net","Henry-Home",
    "Boyd-Net","Boyd-WiFi","Boyd-Home",
    "Mason-WiFi","Mason-Net","Mason-Home",
    "Morales-Home","Morales-WiFi","Morales-Net",
    "Kennedy-WiFi","Kennedy-Net",
    "Warren-Home","Warren-WiFi",
    "Dixon-WiFi","Dixon-Net","Dixon-Home",
    "Ramos-Net","Ramos-WiFi","Ramos-Home",
    "Reyes-WiFi","Reyes-Net","Reyes-Home",
    "Burns-Home","Burns-WiFi","Burns-Net",
    "Gordon-WiFi","Gordon-Net",
    "Shaw-Home","Shaw-WiFi","Shaw-Net",
    "Holmes-WiFi","Holmes-Net","Holmes-Home",
    "Rice-Net","Rice-WiFi","Rice-Home",
    "Robertson-WiFi","Robertson-Net",
    "Hunt-Home","Hunt-WiFi","Hunt-Net",
    "Black-WiFi","Black-Net","Black-Home",
    "Daniels-Net","Daniels-WiFi","Daniels-Home",
    "Palmer-Home","Palmer-WiFi",
    "Mills-WiFi","Mills-Net","Mills-Home",
    "Nichols-Net","Nichols-WiFi",
    "Grant-Home","Grant-WiFi","Grant-Net",
    "Knight-WiFi","Knight-Net","Knight-Home",
    "Ferguson-Net","Ferguson-WiFi",
    "Rose-Home","Rose-WiFi","Rose-Net",
    "Stone-WiFi","Stone-Net","Stone-Home",
    "Hawkins-Net","Hawkins-WiFi",
    "Dunn-Home","Dunn-WiFi","Dunn-Net",
    "Perkins-WiFi","Perkins-Net",
    "Hudson-Home","Hudson-WiFi","Hudson-Net",
    "Spencer-WiFi","Spencer-Net",
    "Gardner-Home","Gardner-WiFi",
    "Stephens-WiFi","Stephens-Net",
    "Payne-Net","Payne-WiFi","Payne-Home",
    "Pierce-Home","Pierce-WiFi",
    "Berry-WiFi","Berry-Net","Berry-Home",
    "Matthews-Net","Matthews-WiFi",
    "Arnold-Home","Arnold-WiFi","Arnold-Net",
    "Wagner-WiFi","Wagner-Net",
    "Willis-Home","Willis-WiFi","Willis-Net",
    "Ray-WiFi","Ray-Net","Ray-Home",
    "Watkins-Net","Watkins-WiFi",
    "Olson-Home","Olson-WiFi","Olson-Net",
    "Carroll-WiFi","Carroll-Net",
    "Duncan-Home","Duncan-WiFi","Duncan-Net",
    "Snyder-WiFi","Snyder-Net","Snyder-Home",
    "Hart-Net","Hart-WiFi","Hart-Home",
    "Cunningham-WiFi","Cunningham-Net",
    "Bradley-Home","Bradley-WiFi",

    // ── Apartment / condo ──────────────────────────────────────────────────
    "Apt101","Apt102","Apt103","Apt104","Apt105","Apt106",
    "Apt201","Apt202","Apt203","Apt204","Apt205","Apt206",
    "Apt301","Apt302","Apt303","Apt304","Apt305","Apt306",
    "Apt401","Apt402","Apt403","Apt404","Apt405","Apt406",
    "Apt-1A","Apt-1B","Apt-1C","Apt-2A","Apt-2B","Apt-2C",
    "Apt-3A","Apt-3B","Apt-3C","Apt-4A","Apt-4B","Apt-4C",
    "Unit1A","Unit1B","Unit1C","Unit2A","Unit2B","Unit2C",
    "Unit3A","Unit3B","Unit3C","Unit4A","Unit4B","Unit4C",
    "Unit101","Unit102","Unit201","Unit202","Unit301","Unit302",
    "#101","#102","#103","#201","#202","#203","#301","#302",
    "#101-wifi","#202-wifi","#303-wifi","#404-wifi","#505-wifi",
    "Suite100","Suite101","Suite200","Suite201","Suite300","Suite301",
    "Floor1-WiFi","Floor2-WiFi","Floor3-WiFi","Floor4-WiFi",
    "Building-A","Building-B","Building-C","Building-D",
    "East-Wing","West-Wing","North-Unit","South-Unit",
    "Tower-A","Tower-B","Annex-WiFi","Main-Building",
    "Apt107","Apt108","Apt207","Apt208","Apt307","Apt308",
    "Rm101","Rm102","Rm201","Rm202","Room101","Room201",
    "Condo-1A","Condo-2B","Condo-3C","Condo-4D",
    "Penthouse","PHWiFi","PH-WiFi","Penthouse-Net",

    // ── Creative / humor / themed ──────────────────────────────────────────
    "FBI Surveillance Van","FBI Surveillance Van 2","FBI Surveillance Van 3",
    "FBI Surveillance Van #4","Not An FBI Van","NSA Mobile Unit",
    "CIA Surveillance","Federal Agent Van","Police Surveillance","DEA Mobile",
    "Pretty Fly For A WiFi","Bill Wi The Science Fi","Wu-Tang LAN","WuTang LAN",
    "Tell My WiFi Love Her","LAN Solo","Han Solo Shot First LAN",
    "Router I Hardly Knew Her","The LAN Before Time","Searching...",
    "Loading...","404 WiFi Not Found","Network Not Found","Error 404: WiFi",
    "Winternet Is Coming","Game of Phones","Use the 5G Luke",
    "The Force Awakens","Obi-WAN Kenobi","Return of the LAN",
    "The Mandalorian Net","Grogu's WiFi","Baby Yoda WiFi",
    "Not the Droids WiFi","The Matrix","Hack If U Can","SkyNet",
    "Skynet Global Defense","Zion WiFi","The Oracle","Agent Smith Net",
    "The Password Is 1234","Password Is Password","No Password Needed",
    "GetOffMyLAN","Get Your Own WiFi","This Is Not Free WiFi",
    "No Free Wifi Here","Buy Your Own Wifi","Yell 'Password' For Key",
    "Password: ItsOnTheBottomOfTheRouter","Password Is Taped to Router",
    "Silence of the LANs","The Promised LAN","LAN of Milk and Honey",
    "IP Freely","I'm Under Your Bed","Panic at the Cisco",
    "it hurts when IP","Series of Tubes","Nacho WiFi","Abraham Linksys",
    "Martin Router King","John Wilkes Bluetooth","Benjamin FranKLIN",
    "Pretty Fly For A WiFi","Drop It Like Its Hotspot",
    "HideYoKidsHideYoWifi","OnionBelongToUs2","TellMyWiFiLoveHer",
    "WiFiMcWiFiFace","Can't Stop The Wifi","Winternet Is Coming",
    "Hogwarts Great Hall","Bag End WiFi","Mordor Net","Rivendell",
    "The Night's Watch","Castle Black WiFi","Winterfell Net",
    "Stark-WiFi","Lannister-Net","Targaryen-5G",
    "Narnia WiFi","Wakanda Forever Net","Avengers HQ",
    "Xavier Institute","Bat Cave WiFi","Daily Planet Net",
    "Virus.exe","Virus_Source","Trojan_Horse","Malware_Lab",
    "Definitely Not FBI","Totally Not Spying","Watching You",
    "Hidden Network","Not Your WiFi","Your Neighbor's WiFi",
    "I Can Hear You","I Can See You","2Spy4U","Spy vs Spy",
    "It's A Trap","This Is A Trap","Admiral Ackbar",
    "Covfefe","Tendies_Network","NPC_WiFi","420Friendly",
    "Doge WiFi","Such WiFi Much Fast","Very Secure Wow",
    "Sponge-Bob-5G","PatrickStar-Net","Krabby-WiFi",
    "Area51 Internal","Roswell Secure Net","Alien Tech WiFi",

    // ── Generic home ───────────────────────────────────────────────────────
    "HOME-2G","HOME-5G","HomeNetwork","HomeWiFi","MyHome","home-wifi",
    "Home-Net","HomeNet","home_network","HOMEWIFI-2G","HOMEWIFI-5G",
    "MyHomeWifi","The Home Network","FamilyWifi","Family-Net",
    "FamilyNetwork","The Family WiFi","MyNetwork","My Network",
    "MyWifi","My WiFi","MyWireless","Wireless","Wireless-N",
    "Wireless-G","Wireless-AC","Wireless-AX","Wireless-6E",
    "PrivateWifi","Private Network","SecureNet","SecureWifi",
    "HomeBase","Base Station","Hub","Central-Net","Central-WiFi",
    "Upstairs","Downstairs","Basement","Garage","Attic","Porch",
    "Living Room WiFi","Kitchen WiFi","Bedroom WiFi","Office WiFi",
    "BackYard","Front Room","MainFloor","TopFloor","Loft",
    "GuestWifi","Guest Network","Guest-WiFi","Guest-Net","guest",
    "guest wifi","visitors","Visitor-WiFi","Guest-5G","IoT-Network",
    "Smart-Home","SmartHome","HomeAutomation","automation","devices",
    "WorkFromHome","Work-WiFi","Office-Net","HomeOffice","RemoteWork",
    "WFH-Net","Zoom-Ready","StreamReady","Gaming","Gaming-WiFi",
    "Game-Net","LowLatency","StreamingTV","Media-Net",
    "2.4GHz Only","5GHz Only","6GHz Only","Dual Band","Tri Band",
    "Fast WiFi","Slow WiFi","Free WiFi Lol","WiFi-1","WiFi-2","WiFi-3",
    "Network1","Network2","Wireless1","Wireless2","wifi","WIFI","WiFi",
    "Internet","TheInternet","World Wide Web","The Web","Broadband",
    "LAN","WLAN","Private LAN","HomeBase-2G","HomeBase-5G",

    // ── Phone hotspot ──────────────────────────────────────────────────────
    "iPhone","John's iPhone","Sarah's iPhone","Mike's iPhone","Emma's iPhone",
    "James's iPhone","Mary's iPhone","David's iPhone","Jessica's iPhone",
    "Lisa's iPhone","Chris's iPhone","Amy's iPhone","Kevin's iPhone",
    "Ryan's iPhone","Ashley's iPhone","Jennifer's iPhone","Matthew's iPhone",
    "Amanda's iPhone","Brian's iPhone","Stephanie's iPhone",
    "AndroidAP","SAMSUNG-A1B2","SAMSUNG-C3D4","Android-Hotspot","MyPhone",
    "Mobile Hotspot","Phone Hotspot","4G LTE Hotspot","5G Hotspot",
    "Verizon-A1B2-iPhone","AT&T-iPhone","T-Mobile-A1B2","Sprint-A1",
    "John's Android","Sarah's Galaxy","Mike's Pixel","Emma's Note",
    "DIRECT-xx-HP","DIRECT-xy-Canon","DIRECT-AB-EPSON","AndroidShare",
    "Personal Hotspot","Mi Mobile Hotspot","OnePlus Hotspot",
    "Galaxy S24-A1","Galaxy-Hotspot","Pixel-7-A1","Pixel Hotspot",

    // ── Canadian ISPs ──────────────────────────────────────────────────────
    "Shaw-A1B2","Shaw-2G-A1","Shaw-5G-B2","ShawWifi-A3C5",
    "Rogers-A1B2","Rogers-2G-A1","Rogers-5G-B2","Rogers-Ignite-A1",
    "Bell WiFi A1B2","Bell-A1B2","Bell-Fibe-A1","BellWiFi-5G",
    "Telus-A1B2","Telus-2G-A1","Telus-5G-B2","TELUS-Optik-A1",
    "Cogeco-A1B2","Videotron-A1","SaskTel-A1","MTS-A1",
    "EastLink-A1","TBayTel-A1","Distributel-A1",

    // ── UK / EU ISPs ───────────────────────────────────────────────────────
    "BT-Hub-A1B2","BT-Hub6-A1","BT-Hub5-A1","BTHub-A1B2","BT-A1B2",
    "BT-Hub-B3C7","BT-Hub-D9E2","BT Smart Hub","BTSmartHub-A1",
    "Sky-A1B2","Sky-B3C7","SkyHub-A1","Sky-BroadbandA1","SKYF9A1B2",
    "Virgin-A1B2","Virgin-Media-A1","VirginMedia-B2","Virgin-Superhub",
    "TalkTalk-A1B2","TalkTalk-B3","EE-A1B2","EE-BrightBox","EE-B3C7",
    "O2-A1B2","O2-Wireless-A1","Three-A1B2","Three-Wifi-B2",
    "Vodafone-A1B2","Vodafone-B3C7","VodafoneConnect-A1","Voda-A1",
    "Plusnet-A1","PlusnetRouter-A1","Plusnet Wireless","IDNet-A1",
    "Freebox-A1B2","SFR-A1B2","Bbox-A1B2","Orange-A1B2",
    "Livebox-A1B2","Bouygues-A1","Numericable-A1","RED-A1",
    "Unitymedia-A1","Telekom-A1B2","1und1-A1","Vodafone-DE-A1",
    "Swisscom-A1","UPC-A1B2","Sunrise-A1","Init7-A1",
    "Ziggo-A1B2","KPN-A1B2","Tele2-A1","XS4ALL-A1","Odido-A1",
    "Fastweb-A1","TIM-A1B2","Wind-A1","Infostrada-A1",
    "Telia-A1B2","Tele2-SE-A1","Telenor-A1","Altibox-A1",
    "Elisa-A1","DNA-A1","Telia-FI-A1","TeliaSonera-A1",

    // ── LATAM ISPs ─────────────────────────────────────────────────────────
    "CLARO-A1B2","Claro-2G-A1","Claro-5G-B2","ClaroWifi-A3",
    "Telmex-A1B2","Telmex-2G","Telmex-5G","TelmexWifi-A1",
    "Megacable-A1B2","Megacable-5G","Totalplay-A1B2","Axtel-A1",
    "Movistar-A1B2","Movistar-5G","MovistarWifi-A1",
    "NET-A1B2","Vivo-A1B2","Oi-A1B2","Tim-A1B2",
    "ETB-A1B2","UNE-A1B2","Claro-CO-A1","Tigo-A1",
    "Entel-A1B2","VTR-A1","Telecentro-A1","Fibertel-A1",
    "Antel-A1","Ufinet-A1","Telecable-A1",

    // ── APAC ISPs ──────────────────────────────────────────────────────────
    "Singtel-A1B2","StarHub-A1B2","M1-A1B2","MyRepublic-A1",
    "TPG-A1B2","ViewQwest-A1","SingtelWiFi-A1",
    "Optus-A1B2","Telstra-A1B2","iiNet-A1B2","NBN-A1","NBN-Co-A1",
    "TPG-AU-A1","Aussie-Broadband-A1","Internode-A1",
    "Spark-A1B2","Vodafone-NZ-A1","2degrees-A1",
    "PLDT-A1B2","Globe-A1B2","Smart-A1B2","Converge-A1",
    "PCCW-A1","HKT-A1B2","HKBN-A1","i-CABLE-A1",
    "Chunghwa-A1","FarEasTone-A1","Taiwan-Mobile-A1",
    "KT-A1B2","SKT-A1B2","LG-Uplus-A1","KT-GiGA-A1",
    "NTT-A1B2","SoftBank-A1","KDDI-A1","au-A1B2","docomo-A1",
    "BSNL-A1B2","Jio-A1B2","Airtel-A1B2","Vi-A1B2","MTNL-A1",
    "PTCL-A1B2","Jazz-A1","Telenor-PK-A1","Zong-A1",
    "True-A1B2","AIS-A1B2","DTAC-A1","TOT-A1","CAT-A1",
    "Unifi-A1B2","Celcom-A1","Maxis-A1","Digi-A1","TIME-A1",

    // ── Small business / commercial bleed ──────────────────────────────────
    "Salon-WiFi","Salon Guest","Barber WiFi","Barbershop-Net",
    "Coffee-Shop","Cafe WiFi","CafeWifi","Coffee-Net","CoffeeShopWifi",
    "Restaurant-Net","ShopNet","Store-WiFi","RetailNet","Shop-Guest",
    "Church-WiFi","Church Guest","ChurchNet","ChurchWiFi-5G",
    "School-WiFi","Library-WiFi","Library-Guest","LibraryWifi",
    "GymWifi","Gym-Guest","Yoga-WiFi","Studio-Net","FitnessWifi",
    "Auto-Shop","Mechanic-WiFi","HVAC-Net","Plumber-WiFi","AC-Service",
    "DocOffice-Guest","Dental-Guest","Medical-WiFi","Clinic-Net",
    "Laundromat-WiFi","Laundry-Net","WashAndDry-WiFi",
    "Hotel-Guest","Motel-WiFi","AirBnB-Net","VRBO-WiFi",
    "RealEstate-WiFi","RealtorNet","OpenHouse-WiFi",
    "Insurance-Guest","LawOffice-Net","AccountingFirm-WiFi",
    "HairSalon-Guest","NailSalon-WiFi","SpaTreatment-Net",
    "TacoTruck-WiFi","FoodTruck-Net","PopUp-WiFi",

    // ── IoT / Smart home ───────────────────────────────────────────────────
    "SmartPlug-A1","SmartBulb-A1","Ring-A1","Ring-Doorbell",
    "Nest-Cam-A1","Arlo-A1B2","Wyze-A1","Blink-A1B2",
    "SmartTV-A1","Roku-A1","FireTV-A1","AppleTV-A1",
    "Chromecast-A1","AndroidTV-A1","Samsung-TV-A1","LG-TV-A1",
    "Printer-A1B2","HP-Print-A1","Canon-A1","Epson-A1B2",
    "EchoSetup-A1","EchoShow-A1","AlexaSetup","SonoseSetup-A1",
    "Hue-bridge-A1","LIFX-A1B2","WeMo-A1","Kasa-A1B2",
    "Ecobee-A1","Honeywell-A1","Thermostat-Net","HVAC-Control",
    "GarageDoor-A1","SecureCam-A1","DoorLock-A1","Alarm-A1",
    "WaterHeater-A1","Washer-A1","Dryer-A1","Dishwasher-A1",

    // ── Extended generic patterns ──────────────────────────────────────────
    "HOME-A2F4","HOME-B3C7","HOME-D1E9","HOME-F4A2","HOME-8C3E",
    "NET-A2F4","NET-B3C7","NET-D1E9","NET-F4A2","NET-9E5C",
    "WIFI-A2F4","WIFI-B3C7","WIFI-D1E9","WIFI-F4A2","WIFI-7B2A",
    "LAN-A2F4","LAN-B3C7","LAN-D1E9","LAN-F4A2","LAN-4C8D",
    "PRIV-A2F4","PRIV-B3C7","PRIV-C9D1","PRIV-7A4E","PRIV-B2F6",
    "RES-12A8B4","RES-3F7E2C","RES-D4B9A1","RES-56CE78","RES-F0E2A9",
    "SEC-A2F4","SEC-B3C7","SEC-D1E9","SEC-F4A2","SEC-3D8E",
    "AP-A2F4","AP-B3C7","AP-D1E9","AP-5C2F",
    "access-A2F4","access-B3C7","access-D1E9",
    "link-A2F4","link-B3C7","link-D1E9","link-7B9C",
    "SSID-A2F4","SSID-B3C7","SSID-D1E9","SSID-F4A2",
    "2GNET-A1B2","5GNET-A1B2","6GNET-A1B2","2G-A1B2","5G-A1B2",

    // ── Street address / house style ───────────────────────────────────────
    "123Main","456Elm","789Oak","321Pine","654Maple","987Birch",
    "1234_WiFi","5678_Net","9012_Home","3456_LAN","7890_WiFi",
    "MainSt-WiFi","ElmSt-Net","OakAve-WiFi","PineRd-Net",
    "Maple-WiFi","Cedar-Net","Birch-Home","Walnut-WiFi",
    "Oak-Hill-WiFi","Pine-Tree-Net","Elm-Creek-WiFi","Cedar-Ridge-Net",
    "Lakeside-WiFi","Riverside-Net","Hillside-Home","Creekside-WiFi",
    "Meadow-Net","Sunrise-WiFi","Sunset-Net","Horizon-WiFi",
    "Valley-View-Net","Mountain-View-WiFi","Ocean-View-Net",
    "Harbor-WiFi","Bay-Area-Net","Seaside-WiFi","Coastal-Net",

    // ── Name + number patterns ─────────────────────────────────────────────
    "Smith2024","Jones2024","Johnson2024","Williams2024","Brown2024",
    "Smith123","Jones456","Johnson789","Davis2023","Miller2022",
    "Smith-2024","Jones-2024","Johnson-2023","Williams-2023",
    "SmithHouse1","JonesHome2","JohnsonPlace3","WilliamsResidence",
    "Casa-de-Smith","Casa-Jones","Chez-Martin","Maison-Dupont",

    // ── Miscellaneous realistic SSIDs ──────────────────────────────────────
    "Fios-A1B2","Verizon-FiOS","FiOS-Router","FiOS-Quantum",
    "Earthlink-A1","EarthLink-WiFi","MindSpring-A1",
    "PeoplePC-A1","NetZero-A1","AOL-WiFi","CompuServe-A1",
    "WIFISPOT","wifi-spot","WifiSpot-A1","HotSpot-A1B2",
    "PublicWifi","Public-WiFi","FreeWifi","Free-WiFi","OpenWifi",
    "Open-Network","OpenNet","CommunityWiFi","Neighborhood-Net",
    "LocalArea","LocalNet","AreaWiFi","ZoneWifi",
    "Network","network","The Network","mynetwork","private",
    "Private","secure","Secure","protected","Protected",
    "internet","INTERNET","wireless","WIRELESS","signal",
    "router","Router","gateway","Gateway","modem","Modem",
    "Admin","admin","ADMIN","default","Default","DEFAULT",
    "Setup","SETUP","Initial","INITIAL","config","Config",
    "LinkSys-Home","Cisco-Home","HP-Home","Dell-Home",
    "Satellite-A1","Dish-WiFi-A1","DirecTV-A1","HughesNet-A1",
    "Mesh-Node-1","Mesh-Node-2","Mesh-Node-3","BackhaulNode",
    "Main-Router","Repeater-A1","Extender-A1","Booster-A1",
    "Bridge-A1","Access-Point-A1","WAP-A1B2","AirStation-A1",
    "2Wire-A1B2","ActionTec-A1","Westel-A1","Thomson-A1",
    "Sagemcom-A1","Arcadyan-A1","ADB-A1","Comtrend-A1",

};
